/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.entities.GUI;

import main.java.DAO.Filtro;
import main.java.utils.Muda;

/**
 *
 * @author Natal
 */
public class DesempenhoNovo extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    Muda muda = new Muda();


    public DesempenhoNovo() {
        initComponents();
    }

     public void preencherDados() {
                Filtro filtro = new Filtro();
                filtro.calcularQuantidadesAdm(lbDescription9, lbDescription10, lbDescription6);
                filtro.calcularQuantidadesLog(lbDescription12, lbDescription14, lbDescription13);
                filtro.calcularQuantidadesProducao(lbDescription17, lbDescription16, lbDescription15);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        kGradientPanel13 = new keeptoo.KGradientPanel();
        lbValues13 = new javax.swing.JLabel();
        lbDescription11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kGradientPanel8 = new keeptoo.KGradientPanel();
        lbValues6 = new javax.swing.JLabel();
        lbDescription6 = new javax.swing.JLabel();
        kGradientPanel11 = new keeptoo.KGradientPanel();
        lbValues8 = new javax.swing.JLabel();
        lbDescription9 = new javax.swing.JLabel();
        kGradientPanel12 = new keeptoo.KGradientPanel();
        lbValues11 = new javax.swing.JLabel();
        lbDescription10 = new javax.swing.JLabel();
        kGradientPanel14 = new keeptoo.KGradientPanel();
        lbValues14 = new javax.swing.JLabel();
        lbDescription12 = new javax.swing.JLabel();
        kGradientPanel15 = new keeptoo.KGradientPanel();
        lbValues15 = new javax.swing.JLabel();
        lbDescription13 = new javax.swing.JLabel();
        kGradientPanel16 = new keeptoo.KGradientPanel();
        lbValues16 = new javax.swing.JLabel();
        lbDescription14 = new javax.swing.JLabel();
        kGradientPanel18 = new keeptoo.KGradientPanel();
        lbValues18 = new javax.swing.JLabel();
        lbDescription16 = new javax.swing.JLabel();
        kGradientPanel17 = new keeptoo.KGradientPanel();
        lbValues17 = new javax.swing.JLabel();
        lbDescription15 = new javax.swing.JLabel();
        kGradientPanel19 = new keeptoo.KGradientPanel();
        lbValues19 = new javax.swing.JLabel();
        lbDescription17 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        kGradientPanel13.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED),
                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        kGradientPanel13.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel13.setkStartColor(new java.awt.Color(102, 0, 102));
        kGradientPanel13.setMaximumSize(new java.awt.Dimension(200, 100));

        lbValues13.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lbValues13.setForeground(new java.awt.Color(255, 255, 255));
        lbValues13.setText("Administrção 13");

        lbDescription11.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lbDescription11.setForeground(new java.awt.Color(255, 255, 255));
        javax.swing.GroupLayout kGradientPanel13Layout = new javax.swing.GroupLayout(kGradientPanel13);
        kGradientPanel13.setLayout(kGradientPanel13Layout);
        kGradientPanel13Layout.setHorizontalGroup(
                kGradientPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kGradientPanel13Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(kGradientPanel13Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbDescription11)
                                        .addComponent(lbValues13))
                                .addContainerGap(115, Short.MAX_VALUE)));
        kGradientPanel13Layout.setVerticalGroup(
                kGradientPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                kGradientPanel13Layout.createSequentialGroup()
                                        .addContainerGap(19, Short.MAX_VALUE)
                                        .addComponent(lbValues13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbDescription11)
                                        .addGap(24, 24, 24)));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 520));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 520));

        kGradientPanel1.setFocusCycleRoot(true);
        kGradientPanel1.setFocusTraversalPolicyProvider(true);
        kGradientPanel1.setInheritsPopupMenu(true);
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setkGradientFocus(300);
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 0, 102));
        kGradientPanel1.setOpaque(false);

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/1.png"))); // NOI18N
        jButton1.setText("Dashbord");
        jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton1.setContentAreaFilled(false);
        jButton1.setDoubleBuffered(true);
        jButton1.setFocusCycleRoot(true);
        jButton1.setFocusTraversalPolicyProvider(true);
        jButton1.setHideActionText(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/4.png"))); // NOI18N
        jButton2.setText("Descarte");
        jButton2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton2.setContentAreaFilled(false);
        jButton2.setDoubleBuffered(true);
        jButton2.setFocusCycleRoot(true);
        jButton2.setFocusTraversalPolicyProvider(true);
        jButton2.setHideActionText(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/3.png"))); // NOI18N
        jButton3.setText("Desempenho");
        jButton3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton3.setContentAreaFilled(false);
        jButton3.setDoubleBuffered(true);
        jButton3.setFocusCycleRoot(true);
        jButton3.setFocusTraversalPolicyProvider(true);
        jButton3.setHideActionText(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/6.png"))); // NOI18N
        jButton4.setText("Editar");
        jButton4.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton4.setContentAreaFilled(false);
        jButton4.setDoubleBuffered(true);
        jButton4.setFocusCycleRoot(true);
        jButton4.setFocusTraversalPolicyProvider(true);
        jButton4.setHideActionText(true);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/8.png"))); // NOI18N
        jButton5.setText("Alterar dados");
        jButton5.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton5.setContentAreaFilled(false);
        jButton5.setDoubleBuffered(true);
        jButton5.setFocusCycleRoot(true);
        jButton5.setFocusTraversalPolicyProvider(true);
        jButton5.setHideActionText(true);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton6.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/8.png"))); // NOI18N
        jButton6.setText("Local de Descarte");
        jButton6.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton6.setContentAreaFilled(false);
        jButton6.setDoubleBuffered(true);
        jButton6.setFocusCycleRoot(true);
        jButton6.setFocusTraversalPolicyProvider(true);
        jButton6.setHideActionText(true);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
                }
            });
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Configuraçoes  ");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/logoP.png"))); // NOI18N
        jLabel2.setText("\n");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
                kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(kGradientPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                                .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 205,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 8, Short.MAX_VALUE)));
        kGradientPanel1Layout.setVerticalGroup(
                kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69,
                                        Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)));

        kGradientPanel8.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED),
                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        kGradientPanel8.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel8.setkStartColor(new java.awt.Color(102, 0, 102));
        kGradientPanel8.setPreferredSize(new java.awt.Dimension(220, 90));
        kGradientPanel8.setMaximumSize(new java.awt.Dimension(220, 90));
        kGradientPanel8.setMinimumSize(new java.awt.Dimension(220, 90));

        lbValues6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lbValues6.setForeground(new java.awt.Color(255, 255, 255));
        lbValues6.setText("Logistica");

        lbDescription6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lbDescription6.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout kGradientPanel8Layout = new javax.swing.GroupLayout(kGradientPanel8);
        kGradientPanel8.setLayout(kGradientPanel8Layout);
        kGradientPanel8Layout.setHorizontalGroup(
                kGradientPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kGradientPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(kGradientPanel8Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbDescription6)
                                        .addComponent(lbValues6))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        kGradientPanel8Layout.setVerticalGroup(
                kGradientPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                kGradientPanel8Layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbValues6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbDescription6)
                                        .addGap(24, 24, 24)));

        kGradientPanel11.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED),
                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        kGradientPanel11.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel11.setkStartColor(new java.awt.Color(102, 0, 102));
        kGradientPanel11.setPreferredSize(new java.awt.Dimension(220, 90));
        kGradientPanel11.setMaximumSize(new java.awt.Dimension(220, 90));
        kGradientPanel11.setMinimumSize(new java.awt.Dimension(220, 90));
        lbValues8.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lbValues8.setForeground(new java.awt.Color(255, 255, 255));
        lbValues8.setText("Não Reclicagem");

        lbDescription9.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lbDescription9.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout kGradientPanel11Layout = new javax.swing.GroupLayout(kGradientPanel11);
        kGradientPanel11.setLayout(kGradientPanel11Layout);
        kGradientPanel11Layout.setHorizontalGroup(
                kGradientPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kGradientPanel11Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(kGradientPanel11Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbDescription9)
                                        .addComponent(lbValues8))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        kGradientPanel11Layout.setVerticalGroup(
                kGradientPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                kGradientPanel11Layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbValues8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbDescription9)
                                        .addGap(24, 24, 24)));

        kGradientPanel12.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED),
                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        kGradientPanel12.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel12.setkStartColor(new java.awt.Color(102, 0, 102));
        kGradientPanel12.setPreferredSize(new java.awt.Dimension(220, 90));
        kGradientPanel12.setMaximumSize(new java.awt.Dimension(220, 90));
        kGradientPanel12.setMinimumSize(new java.awt.Dimension(220, 90));

        lbValues11.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lbValues11.setForeground(new java.awt.Color(255, 255, 255));
        lbValues11.setText("Reclicagem");

        lbDescription10.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lbDescription10.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout kGradientPanel12Layout = new javax.swing.GroupLayout(kGradientPanel12);
        kGradientPanel12.setLayout(kGradientPanel12Layout);
        kGradientPanel12Layout.setHorizontalGroup(
                kGradientPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kGradientPanel12Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(kGradientPanel12Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbDescription10)
                                        .addComponent(lbValues11))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        kGradientPanel12Layout.setVerticalGroup(
                kGradientPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                kGradientPanel12Layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbValues11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbDescription10)
                                        .addGap(24, 24, 24)));

        kGradientPanel14.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED),
                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        kGradientPanel14.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel14.setkStartColor(new java.awt.Color(102, 0, 102));
        kGradientPanel14.setPreferredSize(new java.awt.Dimension(220, 90));
        kGradientPanel14.setMaximumSize(new java.awt.Dimension(220, 90));
        kGradientPanel14.setMinimumSize(new java.awt.Dimension(220, 90));


        lbValues14.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lbValues14.setForeground(new java.awt.Color(255, 255, 255));
        lbValues14.setText("Produção");

        lbDescription12.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lbDescription12.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout kGradientPanel14Layout = new javax.swing.GroupLayout(kGradientPanel14);
        kGradientPanel14.setLayout(kGradientPanel14Layout);
        kGradientPanel14Layout.setHorizontalGroup(
                kGradientPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kGradientPanel14Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(kGradientPanel14Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbDescription12)
                                        .addComponent(lbValues14))
                                .addContainerGap(115, Short.MAX_VALUE)));
        kGradientPanel14Layout.setVerticalGroup(
                kGradientPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                kGradientPanel14Layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbValues14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbDescription12)
                                        .addGap(24, 24, 24)));

        kGradientPanel15.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED),
                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        kGradientPanel15.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel15.setkStartColor(new java.awt.Color(102, 0, 102));
        kGradientPanel15.setPreferredSize(new java.awt.Dimension(220, 90));
        kGradientPanel15.setMaximumSize(new java.awt.Dimension(220, 90));
        kGradientPanel15.setMinimumSize(new java.awt.Dimension(220, 90));

        lbValues15.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lbValues15.setForeground(new java.awt.Color(255, 255, 255));
        lbValues15.setText("Não Reciclagem");

        lbDescription13.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lbDescription13.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout kGradientPanel15Layout = new javax.swing.GroupLayout(kGradientPanel15);
        kGradientPanel15.setLayout(kGradientPanel15Layout);
        kGradientPanel15Layout.setHorizontalGroup(
                kGradientPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kGradientPanel15Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(kGradientPanel15Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbDescription13)
                                        .addComponent(lbValues15))
                                .addContainerGap(115, Short.MAX_VALUE)));
        kGradientPanel15Layout.setVerticalGroup(
                kGradientPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                kGradientPanel15Layout.createSequentialGroup()
                                        .addContainerGap(19, Short.MAX_VALUE)
                                        .addComponent(lbValues15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbDescription13)
                                        .addGap(24, 24, 24)));

        kGradientPanel16.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED),
                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        kGradientPanel16.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel16.setkStartColor(new java.awt.Color(102, 0, 102));
        kGradientPanel16.setPreferredSize(new java.awt.Dimension(220, 90));
        kGradientPanel16.setMaximumSize(new java.awt.Dimension(220, 90));
        kGradientPanel16.setMinimumSize(new java.awt.Dimension(220, 90));

        lbValues16.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lbValues16.setForeground(new java.awt.Color(255, 255, 255));
        lbValues16.setText("Reciclagem");

        lbDescription14.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lbDescription14.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout kGradientPanel16Layout = new javax.swing.GroupLayout(kGradientPanel16);
        kGradientPanel16.setLayout(kGradientPanel16Layout);
        kGradientPanel16Layout.setHorizontalGroup(
                kGradientPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kGradientPanel16Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(kGradientPanel16Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbDescription14)
                                        .addComponent(lbValues16))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        kGradientPanel16Layout.setVerticalGroup(
                kGradientPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                kGradientPanel16Layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbValues16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbDescription14)
                                        .addGap(24, 24, 24)));

        kGradientPanel18.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED),
                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        kGradientPanel18.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel18.setkStartColor(new java.awt.Color(102, 0, 102));
        kGradientPanel18.setPreferredSize(new java.awt.Dimension(220, 90));
        kGradientPanel18.setMaximumSize(new java.awt.Dimension(220, 90));
        kGradientPanel18.setMinimumSize(new java.awt.Dimension(220, 90));
        lbValues18.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lbValues18.setForeground(new java.awt.Color(255, 255, 255));
        lbValues18.setText("Reciclagem");

        lbDescription16.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lbDescription16.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout kGradientPanel18Layout = new javax.swing.GroupLayout(kGradientPanel18);
        kGradientPanel18.setLayout(kGradientPanel18Layout);
        kGradientPanel18Layout.setHorizontalGroup(
                kGradientPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kGradientPanel18Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(kGradientPanel18Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbDescription16)
                                        .addComponent(lbValues18))
                                .addContainerGap(115, Short.MAX_VALUE)));
        kGradientPanel18Layout.setVerticalGroup(
                kGradientPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                kGradientPanel18Layout.createSequentialGroup()
                                        .addContainerGap(19, Short.MAX_VALUE)
                                        .addComponent(lbValues18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbDescription16)
                                        .addGap(24, 24, 24)));

        kGradientPanel17.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED),
                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        kGradientPanel17.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel17.setkStartColor(new java.awt.Color(102, 0, 102));
        kGradientPanel17.setPreferredSize(new java.awt.Dimension(220, 90));
        kGradientPanel17.setMaximumSize(new java.awt.Dimension(220, 90));
        kGradientPanel17.setMinimumSize(new java.awt.Dimension(220, 90));

        lbValues17.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lbValues17.setForeground(new java.awt.Color(255, 255, 255));
        lbValues17.setText("Não Reciclagem");

        lbDescription15.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lbDescription15.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout kGradientPanel17Layout = new javax.swing.GroupLayout(kGradientPanel17);
        kGradientPanel17.setLayout(kGradientPanel17Layout);
        kGradientPanel17Layout.setHorizontalGroup(
                kGradientPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kGradientPanel17Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(kGradientPanel17Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbDescription15)
                                        .addComponent(lbValues17))
                                .addContainerGap(115, Short.MAX_VALUE)));
        kGradientPanel17Layout.setVerticalGroup(
                kGradientPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                kGradientPanel17Layout.createSequentialGroup()
                                        .addContainerGap(19, Short.MAX_VALUE)
                                        .addComponent(lbValues17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbDescription15)
                                        .addGap(24, 24, 24)));

        kGradientPanel19.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED),
                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        kGradientPanel19.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel19.setkStartColor(new java.awt.Color(102, 0, 102));
        kGradientPanel19.setPreferredSize(new java.awt.Dimension(220, 90));
        kGradientPanel19.setMaximumSize(new java.awt.Dimension(220, 90));
        kGradientPanel19.setMinimumSize(new java.awt.Dimension(220, 90));


        lbValues19.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lbValues19.setForeground(new java.awt.Color(255, 255, 255));
        lbValues19.setText("Administração");

        lbDescription17.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lbDescription17.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout kGradientPanel19Layout = new javax.swing.GroupLayout(kGradientPanel19);
        kGradientPanel19.setLayout(kGradientPanel19Layout);
        kGradientPanel19Layout.setHorizontalGroup(
                kGradientPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kGradientPanel19Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(kGradientPanel19Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbDescription17)
                                        .addComponent(lbValues19))
                                .addContainerGap(115, Short.MAX_VALUE)));
        kGradientPanel19Layout.setVerticalGroup(
                kGradientPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                kGradientPanel19Layout.createSequentialGroup()
                                        .addContainerGap(19, Short.MAX_VALUE)
                                        .addComponent(lbValues19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbDescription17)
                                        .addGap(24, 24, 24)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(kGradientPanel14,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(kGradientPanel8,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(33, 33, 33)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(kGradientPanel16,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(kGradientPanel12,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(33, 33, 33))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(kGradientPanel19, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)
                                                .addComponent(kGradientPanel18, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33,
                                                        Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(kGradientPanel17, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(kGradientPanel15, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(kGradientPanel11, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(36, 36, 36)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(kGradientPanel19, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(kGradientPanel17, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(kGradientPanel18, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(kGradientPanel14, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(kGradientPanel16, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(kGradientPanel15, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(kGradientPanel11, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(kGradientPanel12, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(kGradientPanel8, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(94, 94, 94)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));

        setSize(new java.awt.Dimension(1016, 528));
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        muda.Home();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        muda.descartado();
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        muda.desempenho();
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        muda.Editar();
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        muda.perfil();
    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        muda.LocalDescarte();
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesempenhoNovo.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesempenhoNovo.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesempenhoNovo.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesempenhoNovo.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>


    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel11;
    private keeptoo.KGradientPanel kGradientPanel12;
    private keeptoo.KGradientPanel kGradientPanel13;
    private keeptoo.KGradientPanel kGradientPanel14;
    private keeptoo.KGradientPanel kGradientPanel15;
    private keeptoo.KGradientPanel kGradientPanel16;
    private keeptoo.KGradientPanel kGradientPanel17;
    private keeptoo.KGradientPanel kGradientPanel18;
    private keeptoo.KGradientPanel kGradientPanel19;
    private keeptoo.KGradientPanel kGradientPanel8;
    private javax.swing.JLabel lbDescription10;
    private javax.swing.JLabel lbDescription11;
    private javax.swing.JLabel lbDescription12;
    private javax.swing.JLabel lbDescription13;
    private javax.swing.JLabel lbDescription14;
    private javax.swing.JLabel lbDescription15;
    private javax.swing.JLabel lbDescription16;
    private javax.swing.JLabel lbDescription17;
    private javax.swing.JLabel lbDescription6;
    private javax.swing.JLabel lbDescription9;
    private javax.swing.JLabel lbValues11;
    private javax.swing.JLabel lbValues13;
    private javax.swing.JLabel lbValues14;
    private javax.swing.JLabel lbValues15;
    private javax.swing.JLabel lbValues16;
    private javax.swing.JLabel lbValues17;
    private javax.swing.JLabel lbValues18;
    private javax.swing.JLabel lbValues19;
    private javax.swing.JLabel lbValues6;
    private javax.swing.JLabel lbValues8;
    // End of variables declaration
}
