/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.entities.GUI;

import main.java.DAO.DatabaseQuery;
import main.java.DAO.Filtro;
import main.java.utils.Muda;

/**
 *
 * @author Natal
 */
public class Menu extends javax.swing.JFrame {

        /**
         * Creates new form Menu
         * 
         */
        Muda muda = new Muda();

        public Menu() {
                initComponents();

        }

        public void preencherDados() {
                Filtro filtro = new Filtro();
                filtro.calcularQuantidades(lbDescription, lbDescription1, lbDescription2);
        }

        public void preencherTabela() {
                DatabaseQuery dados = new DatabaseQuery();
                dados.preencherTabela(jTable1);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jRadioButton1 = new javax.swing.JRadioButton();
                jPanel1 = new javax.swing.JPanel();
                kGradientPanel1 = new keeptoo.KGradientPanel();
                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();
                jButton3 = new javax.swing.JButton();
                jButton4 = new javax.swing.JButton();
                jButton5 = new javax.swing.JButton();
                jButton6 = new javax.swing.JButton();

                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                kGradientPanel2 = new keeptoo.KGradientPanel();
                lbDescription = new javax.swing.JLabel();
                lbValues = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                kGradientPanel3 = new keeptoo.KGradientPanel();
                lbValues1 = new javax.swing.JLabel();
                lbDescription1 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                kGradientPanel4 = new keeptoo.KGradientPanel();
                lbValues2 = new javax.swing.JLabel();
                lbDescription2 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();

                jRadioButton1.setText("jRadioButton1");

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));
                jPanel1.setMaximumSize(new java.awt.Dimension(1000, 520));
                jPanel1.setMinimumSize(new java.awt.Dimension(1000, 520));

                kGradientPanel1.setFocusCycleRoot(true);
                kGradientPanel1.setFocusTraversalPolicyProvider(true);
                kGradientPanel1.setInheritsPopupMenu(true);
                kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 0));
                kGradientPanel1.setkGradientFocus(300);
                kGradientPanel1.setkStartColor(new java.awt.Color(102, 0, 102));
                kGradientPanel1.setOpaque(false);

                jButton1.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
                jButton1.setForeground(new java.awt.Color(255, 255, 255));
                jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/1.png"))); // NOI18N
                jButton1.setText("Dashbord");
                jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
                jButton1.setContentAreaFilled(false);
                jButton1.setDoubleBuffered(true);
                jButton1.setFocusCycleRoot(true);
                jButton1.setFocusTraversalPolicyProvider(true);
                jButton1.setHideActionText(true);
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jButton2.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
                jButton2.setForeground(new java.awt.Color(255, 255, 255));
                jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/4.png"))); // NOI18N
                jButton2.setText("Descarte");
                jButton2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
                jButton2.setContentAreaFilled(false);
                jButton2.setDoubleBuffered(true);
                jButton2.setFocusCycleRoot(true);
                jButton2.setFocusTraversalPolicyProvider(true);
                jButton2.setHideActionText(true);
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });

                jButton3.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
                jButton3.setForeground(new java.awt.Color(255, 255, 255));
                jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/3.png"))); // NOI18N
                jButton3.setText("Desempenho");
                jButton3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
                jButton3.setContentAreaFilled(false);
                jButton3.setDoubleBuffered(true);
                jButton3.setFocusCycleRoot(true);
                jButton3.setFocusTraversalPolicyProvider(true);
                jButton3.setHideActionText(true);
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                        }
                });

                jButton4.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
                jButton4.setForeground(new java.awt.Color(255, 255, 255));
                jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/6.png"))); // NOI18N
                jButton4.setText("Editar");
                jButton4.setBorder(javax.swing.BorderFactory.createCompoundBorder());
                jButton4.setContentAreaFilled(false);
                jButton4.setDoubleBuffered(true);
                jButton4.setFocusCycleRoot(true);
                jButton4.setFocusTraversalPolicyProvider(true);
                jButton4.setHideActionText(true);
                jButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton4ActionPerformed(evt);
                        }
                });

                jButton5.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
                jButton5.setForeground(new java.awt.Color(255, 255, 255));
                jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/8.png"))); // NOI18N
                jButton5.setText("Alterar dados");
                jButton5.setBorder(javax.swing.BorderFactory.createCompoundBorder());
                jButton5.setContentAreaFilled(false);
                jButton5.setDoubleBuffered(true);
                jButton5.setFocusCycleRoot(true);
                jButton5.setFocusTraversalPolicyProvider(true);
                jButton5.setHideActionText(true);
                jButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton5ActionPerformed(evt);
                        }
                });

                jButton6.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
                jButton6.setForeground(new java.awt.Color(255, 255, 255));
                jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/8.png"))); // NOI18N
                jButton6.setText("Local de Descarte");
                jButton6.setBorder(javax.swing.BorderFactory.createCompoundBorder());
                jButton6.setContentAreaFilled(false);
                jButton6.setDoubleBuffered(true);
                jButton6.setFocusCycleRoot(true);
                jButton6.setFocusTraversalPolicyProvider(true);
                jButton6.setHideActionText(true);
                jButton6.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton6ActionPerformed(evt);
                        }
                });
                
                jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("Configuraçoes  ");

                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/logoP.png"))); 
                jLabel2.setText("\n");

                javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
                kGradientPanel1.setLayout(kGradientPanel1Layout);
                kGradientPanel1Layout.setHorizontalGroup(
                                kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel1)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                                .addGroup(kGradientPanel1Layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(kGradientPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                false)
                                                                                                .addComponent(jButton5,
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                229,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jButton4,
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jButton3,
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jButton6,
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jButton2,
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jButton1,
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE))
                                                                                .addComponent(jLabel2,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                205,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(0, 4, Short.MAX_VALUE)));
                kGradientPanel1Layout.setVerticalGroup(
                                kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                132,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jButton1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                36,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButton2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                36,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButton3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                36,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jButton6,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                36,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButton4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                36,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButton5,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                36,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(78, 78, 78)));

                kGradientPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                                new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED),
                                new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
                kGradientPanel2.setkEndColor(new java.awt.Color(102, 0, 102));
                kGradientPanel2.setkGradientFocus(100);
                kGradientPanel2.setkStartColor(new java.awt.Color(0, 0, 0));

                lbDescription.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
                lbDescription.setForeground(new java.awt.Color(255, 255, 255));

                lbValues.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
                lbValues.setForeground(new java.awt.Color(255, 255, 255));
                lbValues.setText("Total");

                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/7.png"))); // NOI18N

                javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
                kGradientPanel2.setLayout(kGradientPanel2Layout);
                kGradientPanel2Layout.setHorizontalGroup(
                                kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(kGradientPanel2Layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(lbDescription)
                                                                                .addComponent(lbValues)
                                                                                .addComponent(jLabel6))
                                                                .addContainerGap(83, Short.MAX_VALUE)));
                kGradientPanel2Layout.setVerticalGroup(
                                kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                kGradientPanel2Layout.createSequentialGroup()
                                                                                .addContainerGap(
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel6)
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(lbValues)
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(lbDescription)
                                                                                .addGap(18, 18, 18)));

                kGradientPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                                new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED),
                                new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
                kGradientPanel3.setkEndColor(new java.awt.Color(102, 0, 102));
                kGradientPanel3.setkGradientFocus(100);
                kGradientPanel3.setkStartColor(new java.awt.Color(0, 0, 0));

                lbValues1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
                lbValues1.setForeground(new java.awt.Color(255, 255, 255));
                lbValues1.setText("Reciclagem");

                lbDescription1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
                lbDescription1.setForeground(new java.awt.Color(255, 255, 255));

                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/7.png"))); // NOI18N

                javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
                kGradientPanel3.setLayout(kGradientPanel3Layout);
                kGradientPanel3Layout.setHorizontalGroup(
                                kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(kGradientPanel3Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(kGradientPanel3Layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(lbDescription1)
                                                                                .addComponent(lbValues1)
                                                                                .addComponent(jLabel4))
                                                                .addContainerGap(81, Short.MAX_VALUE))
                                                .addGroup(kGradientPanel3Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(kGradientPanel3Layout.createSequentialGroup()
                                                                                .addGap(16, 16, 16)
                                                                                .addComponent(jLabel5)
                                                                                .addContainerGap(135,
                                                                                                Short.MAX_VALUE))));
                kGradientPanel3Layout.setVerticalGroup(
                                kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                kGradientPanel3Layout.createSequentialGroup()
                                                                                .addContainerGap(18, Short.MAX_VALUE)
                                                                                .addComponent(jLabel4)
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(lbValues1)
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(lbDescription1)
                                                                                .addGap(22, 22, 22))
                                                .addGroup(kGradientPanel3Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(kGradientPanel3Layout.createSequentialGroup()
                                                                                .addGap(17, 17, 17)
                                                                                .addComponent(jLabel5)
                                                                                .addContainerGap(82,
                                                                                                Short.MAX_VALUE))));

                kGradientPanel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                                new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED),
                                new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
                kGradientPanel4.setkEndColor(new java.awt.Color(102, 0, 102));
                kGradientPanel4.setkGradientFocus(100);
                kGradientPanel4.setkStartColor(new java.awt.Color(0, 0, 0));

                lbValues2.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
                lbValues2.setForeground(new java.awt.Color(255, 255, 255));
                lbValues2.setText("Não Reciclagem");

                lbDescription2.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
                lbDescription2.setForeground(new java.awt.Color(255, 255, 255));

                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/7.png"))); // NOI18N

                javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
                kGradientPanel4.setLayout(kGradientPanel4Layout);
                kGradientPanel4Layout.setHorizontalGroup(
                                kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(kGradientPanel4Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(kGradientPanel4Layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(lbDescription2)
                                                                                .addComponent(lbValues2)
                                                                                .addComponent(jLabel7))
                                                                .addContainerGap(42, Short.MAX_VALUE)));
                kGradientPanel4Layout.setVerticalGroup(
                                kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                kGradientPanel4Layout.createSequentialGroup()
                                                                                .addContainerGap(
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel7)
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(lbValues2)
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(lbDescription2)
                                                                                .addGap(22, 22, 22)));

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null },
                                                { null, null, null, null, null }
                                },
                                new String[] {
                                                "ID", "NOME", "TIPO", "QUANTIDADE", "DATA"
                                }) {
                        boolean[] canEdit = new boolean[] {
                                        false, false, false, false, false // All columns are non-editable now
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit[columnIndex];
                        }
                });
                jScrollPane1.setViewportView(jTable1);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(kGradientPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(38, 38, 38)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(kGradientPanel2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(45, 45, 45)
                                                                                                .addComponent(kGradientPanel3,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                45,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(kGradientPanel4,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(jScrollPane1))
                                                                .addGap(38, 38, 38)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(kGradientPanel1,
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(22, 22, 22)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(kGradientPanel2,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(kGradientPanel3,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(kGradientPanel4,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                303,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(53, Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                setSize(new java.awt.Dimension(1016, 528));
                setLocationRelativeTo(null);

        }// </editor-fold>

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
                muda.Home();
        }

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
                muda.descartado();
        }

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
                muda.desempenho();
        }

        private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
                muda.Editar();
        }

        private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
                muda.perfil();
        }
        private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
                muda.LocalDescarte();
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new Menu().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JButton jButton4;
        private javax.swing.JButton jButton5;
        private javax.swing.JButton jButton6;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JRadioButton jRadioButton1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable jTable1;
        private keeptoo.KGradientPanel kGradientPanel1;
        private keeptoo.KGradientPanel kGradientPanel2;
        private keeptoo.KGradientPanel kGradientPanel3;
        private keeptoo.KGradientPanel kGradientPanel4;
        private javax.swing.JLabel lbDescription;
        private javax.swing.JLabel lbDescription1;
        private javax.swing.JLabel lbDescription2;
        private javax.swing.JLabel lbValues;
        private javax.swing.JLabel lbValues1;
        private javax.swing.JLabel lbValues2;
        // End of variables declaration
}
