/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.entities.GUI;

import javax.swing.JOptionPane;

import main.java.entities.User;
import main.java.utils.Muda;

/**
 *
 * @author Natal
 */
public class PerfilNovo extends javax.swing.JFrame {

        /**
         * Creates new form Menu
         */
        public PerfilNovo() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jRadioButton1 = new javax.swing.JRadioButton();
                kGradientPanel13 = new keeptoo.KGradientPanel();
                lbValues13 = new javax.swing.JLabel();
                lbDescription11 = new javax.swing.JLabel();
                popupMenu1 = new java.awt.PopupMenu();
                jPanel1 = new javax.swing.JPanel();
                jButton6 = new javax.swing.JButton();
                jTextField2 = new javax.swing.JTextField();
                jLabel1 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jPasswordField1 = new javax.swing.JPasswordField();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jTextField3 = new javax.swing.JTextField();
                jLabel6 = new javax.swing.JLabel();
                jTextField4 = new javax.swing.JTextField();
                jLabel7 = new javax.swing.JLabel();
                jTextField5 = new javax.swing.JTextField();
                jLabel8 = new javax.swing.JLabel();
                jTextField6 = new javax.swing.JTextField();
                jLabel9 = new javax.swing.JLabel();
                jTextField7 = new javax.swing.JTextField();
                jTextField8 = new javax.swing.JTextField();
                jLabel10 = new javax.swing.JLabel();
                jLabel11 = new javax.swing.JLabel();
                jTextField9 = new javax.swing.JTextField();
                jButton1 = new javax.swing.JButton();
                jTextField1 = new javax.swing.JTextField();
                kGradientPanel1 = new keeptoo.KGradientPanel();
                jLabel2 = new javax.swing.JLabel();
                jButton2 = new javax.swing.JButton();
                jButton3 = new javax.swing.JButton();
                jButton4 = new javax.swing.JButton();
                jButton5 = new javax.swing.JButton();
                jButton8 = new javax.swing.JButton();
                jButton9 = new javax.swing.JButton();
                jLabel12 = new javax.swing.JLabel();

                jRadioButton1.setText("jRadioButton1");

                kGradientPanel13.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED),
                                javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
                kGradientPanel13.setkEndColor(new java.awt.Color(0, 0, 0));
                kGradientPanel13.setkStartColor(new java.awt.Color(102, 0, 102));
                kGradientPanel13.setMaximumSize(new java.awt.Dimension(200, 100));

                lbValues13.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
                lbValues13.setForeground(new java.awt.Color(255, 255, 255));
                lbValues13.setText("Total");

                lbDescription11.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
                lbDescription11.setForeground(new java.awt.Color(255, 255, 255));
                lbDescription11.setText("Description");

                javax.swing.GroupLayout kGradientPanel13Layout = new javax.swing.GroupLayout(kGradientPanel13);
                kGradientPanel13.setLayout(kGradientPanel13Layout);
                kGradientPanel13Layout.setHorizontalGroup(
                                kGradientPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(kGradientPanel13Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(kGradientPanel13Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(lbDescription11)
                                                                                .addComponent(lbValues13))
                                                                .addContainerGap(115, Short.MAX_VALUE)));
                kGradientPanel13Layout.setVerticalGroup(
                                kGradientPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                kGradientPanel13Layout.createSequentialGroup()
                                                                                .addContainerGap(19, Short.MAX_VALUE)
                                                                                .addComponent(lbValues13)
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(lbDescription11)
                                                                                .addGap(24, 24, 24)));

                popupMenu1.setLabel("popupMenu1");

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));
                jPanel1.setMaximumSize(new java.awt.Dimension(1000, 520));
                jPanel1.setMinimumSize(new java.awt.Dimension(1000, 520));

                jButton6.setBackground(new java.awt.Color(51, 0, 51));
                jButton6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jButton6.setForeground(new java.awt.Color(255, 255, 255));
                jButton6.setText("SALVAR");
                jButton6.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                                new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED),
                                new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
                jButton6.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton6ActionPerformed(evt);
                        }
                });

                jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
                jLabel1.setText("Senha");

                jLabel3.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
                jLabel3.setText("Nome");

                jLabel4.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
                jLabel4.setText("Confirmar");

                jLabel5.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
                jLabel5.setText("Email");

                jLabel6.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
                jLabel6.setText("Telefone");

                jLabel7.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
                jLabel7.setText("UF");

                jLabel8.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
                jLabel8.setText("CEP");

                jLabel9.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
                jLabel9.setText("Rua");

                jTextField8.setEnabled(false);

                jLabel10.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
                jLabel10.setText("N°");

                jLabel11.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
                jLabel11.setText("Cidade");

                jButton1.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/search.png"))); // NOI18N
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton1ActionPerformed(evt);
                }});
                

                kGradientPanel1.setFocusCycleRoot(true);
                kGradientPanel1.setFocusTraversalPolicyProvider(true);
                kGradientPanel1.setInheritsPopupMenu(true);
                kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 0));
                kGradientPanel1.setkGradientFocus(300);
                kGradientPanel1.setkStartColor(new java.awt.Color(102, 0, 102));
                kGradientPanel1.setOpaque(false);

                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/logoP.png"))); // NOI18N

                jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
                jButton2.setForeground(new java.awt.Color(255, 255, 255));
                jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/3.png"))); // NOI18N
                jButton2.setText("Desempenho");
                jButton2.setBorder(null);
                jButton2.setContentAreaFilled(false);
                jButton2.setDoubleBuffered(true);
                jButton2.setFocusCycleRoot(true);
                jButton2.setFocusTraversalPolicyProvider(true);
                jButton2.setHideActionText(true);
                jButton2.setInheritsPopupMenu(true);
                jButton2.setRequestFocusEnabled(false);
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });

                jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
                jButton3.setForeground(new java.awt.Color(255, 255, 255));
                jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/4.png"))); // NOI18N
                jButton3.setText("Descarte");
                jButton3.setBorder(null);
                jButton3.setContentAreaFilled(false);
                jButton3.setDoubleBuffered(true);
                jButton3.setFocusCycleRoot(true);
                jButton3.setFocusTraversalPolicyProvider(true);
                jButton3.setHideActionText(true);
                jButton3.setInheritsPopupMenu(true);
                jButton3.setRequestFocusEnabled(false);
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                        }
                });

                jButton4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
                jButton4.setForeground(new java.awt.Color(255, 255, 255));
                jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/1.png"))); // NOI18N
                jButton4.setText("Dashbord");
                jButton4.setBorder(null);
                jButton4.setContentAreaFilled(false);
                jButton4.setDoubleBuffered(true);
                jButton4.setFocusCycleRoot(true);
                jButton4.setFocusTraversalPolicyProvider(true);
                jButton4.setHideActionText(true);
                jButton4.setInheritsPopupMenu(true);
                jButton4.setRequestFocusEnabled(false);
                jButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton4ActionPerformed(evt);
                        }
                });
                jButton9.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
                jButton9.setForeground(new java.awt.Color(255, 255, 255));
                jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/8.png"))); // NOI18N
                jButton9.setText("Local de descarte");
                jButton9.setBorder(null);
                jButton9.setContentAreaFilled(false);
                jButton9.setDoubleBuffered(true);
                jButton9.setFocusCycleRoot(true);
                jButton9.setFocusTraversalPolicyProvider(true);
                jButton9.setHideActionText(true);
                jButton9.setInheritsPopupMenu(true);
                jButton9.setRequestFocusEnabled(false);
                jButton9.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton9ActionPerformed(evt);
                        }
                });

                jButton5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
                jButton5.setForeground(new java.awt.Color(255, 255, 255));
                jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/6.png"))); // NOI18N
                jButton5.setText("Editor");
                jButton5.setBorder(null);
                jButton5.setContentAreaFilled(false);
                jButton5.setDoubleBuffered(true);
                jButton5.setFocusCycleRoot(true);
                jButton5.setFocusTraversalPolicyProvider(true);
                jButton5.setHideActionText(true);
                jButton5.setInheritsPopupMenu(true);
                jButton5.setRequestFocusEnabled(false);
                jButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton5ActionPerformed(evt);
                        }
                });

                jButton8.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
                jButton8.setForeground(new java.awt.Color(255, 255, 255));
                jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/images/8.png"))); // NOI18N
                jButton8.setText("Alterar Dados");
                jButton8.setBorder(null);
                jButton8.setContentAreaFilled(false);
                jButton8.setDoubleBuffered(true);
                jButton8.setFocusCycleRoot(true);
                jButton8.setFocusTraversalPolicyProvider(true);
                jButton8.setHideActionText(true);
                jButton8.setInheritsPopupMenu(true);
                jButton8.setRequestFocusEnabled(false);

                jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
                jLabel12.setForeground(new java.awt.Color(255, 255, 255));
                jLabel12.setText("Configuraçoes");

                javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
                kGradientPanel1.setLayout(kGradientPanel1Layout);
                kGradientPanel1Layout.setHorizontalGroup(
                                kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel2,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                274, Short.MAX_VALUE))
                                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                                .addGroup(kGradientPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(kGradientPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(36, 36, 36)
                                                                                                .addGroup(kGradientPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(jButton8,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                185,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGroup(kGradientPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(jButton3,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                205,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGroup(kGradientPanel1Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                false)
                                                                                                                                                .addComponent(jButton5,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(jButton4,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(jButton2,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                205,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(jButton9,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                205,
                                                                                                                                                                Short.MAX_VALUE)))))
                                                                                .addGroup(kGradientPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addComponent(jLabel12)))
                                                                .addGap(0, 0, Short.MAX_VALUE)));
                kGradientPanel1Layout.setVerticalGroup(
                                kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                151,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jButton4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                26,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jButton3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                26,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jButton2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                26,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jButton9,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                26,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(11, 11, 11)
                                                                .addComponent(jButton5)
                                                                .addGap(24, 24, 24)
                                                                .addComponent(jLabel12)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jButton8)
                                                                .addGap(0, 0, Short.MAX_VALUE)));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(kGradientPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(113, 113, 113)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(121, 121, 121)
                                                                                                .addComponent(jButton6,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                138,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jTextField2,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                229,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel3)
                                                                                                                .addComponent(jLabel6)
                                                                                                                .addComponent(jLabel1))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jLabel4)
                                                                                                                .addComponent(jLabel5)
                                                                                                                .addComponent(jPasswordField1)))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel9)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(jTextField7))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                                                .addComponent(jLabel11)
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                .addComponent(jTextField9,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                274,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(jLabel8,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                34,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(jTextField4,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                251,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                .addComponent(jButton1,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                36,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(jLabel7)
                                                                                                                .addComponent(jLabel10))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jTextField8,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                98,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jTextField6)))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jTextField5,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                229,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jTextField3))
                                                                                .addComponent(jTextField1))
                                                                .addContainerGap(128, Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(75, 75, 75)
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jTextField1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                22,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(jLabel1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                25,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jPasswordField1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jTextField2,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel5,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                19,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel6,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                19,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jTextField5,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jTextField3))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel1Layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jTextField8,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel7)
                                                                                                                .addComponent(jButton1))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jLabel8)
                                                                                                .addComponent(jTextField4,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel1Layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jTextField9,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel10)
                                                                                                                .addComponent(jTextField6,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(jLabel11))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel9)
                                                                                .addComponent(jTextField7,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(40, 40, 40)
                                                                .addComponent(jButton6,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                46,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(64, 64, 64))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(kGradientPanel1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addContainerGap()));

                jTextField1.getAccessibleContext().setAccessibleDescription("");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addContainerGap()));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                setSize(new java.awt.Dimension(1020, 528));
                setLocationRelativeTo(null);
        }// </editor-fold>

        Muda muda = new Muda();

        private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
                muda.Editar();
        }

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
                muda.desempenho();
        }

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
                muda.descartado();
        }

        private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
                muda.Home();
        }
        private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
                muda.LocalDescarte();
        }

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
                String cep = jTextField4.getText();
                User user = new User();
                user.consultCep(cep,jTextField8,jTextField9,jTextField7);
                
        }

        private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
                String name = jTextField1.getText();
                String senha = jTextField2.getText();
                String confirmar = jPasswordField1.getText();
                String telefoneSRT = jTextField5.getText();
                String email = jTextField3.getText();
                String cep = jTextField4.getText();
                String uf = jTextField8.getText();
                String cidade = jTextField9.getText();
                String N = jTextField6.getText();
                String rua = jTextField7.getText();
                
                // Verifica se o telefone e o CEP contêm apenas números
                if (!telefoneSRT.matches("[0-9]+") || !cep.matches("[0-9]+")) {
                    JOptionPane.showMessageDialog(this, "Telefone ou CEP inválido. Por favor, insira apenas números.");
                    return; 
                }
                
                if (senha.equals(confirmar)) {
                    try {
                        User user = new User(name, email, senha, telefoneSRT, cep, uf, cidade, N, rua);
                        user.alterarDados();
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "Telefone ou CEP inválido.");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Senha e confirmação não coincidem.");
                }
            }

        public static void main(String args[]) {

        }

        // Variables declaration - do not modify
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JButton jButton4;
        private javax.swing.JButton jButton5;
        private javax.swing.JButton jButton6;
        private javax.swing.JButton jButton8;
        private javax.swing.JButton jButton9;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPasswordField jPasswordField1;
        private javax.swing.JRadioButton jRadioButton1;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JTextField jTextField2;
        private javax.swing.JTextField jTextField3;
        private javax.swing.JTextField jTextField4;
        private javax.swing.JTextField jTextField5;
        private javax.swing.JTextField jTextField6;
        private javax.swing.JTextField jTextField7;
        private javax.swing.JTextField jTextField8;
        private javax.swing.JTextField jTextField9;
        private keeptoo.KGradientPanel kGradientPanel1;
        private keeptoo.KGradientPanel kGradientPanel13;
        private javax.swing.JLabel lbDescription11;
        private javax.swing.JLabel lbValues13;
        private java.awt.PopupMenu popupMenu1;
        // End of variables declaration
}
